output_root: '/shared/xinyang/CutLER/datasets/imagenet_stego_seg'
pytorch_data_dir: '/shared/xinyang/CutLER/datasets/resize_imagenet'
experiment_name: "imagenet"
res: 448
# batch_size: 8
batch_size: 16
# num_workers: 1
num_workers: 4
run_picie: False
# run_picie: True
run_crf: False
# run_crf: True
# run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False

model_paths:
  - "../saved_models/cocostuff27_vit_base_5.ckpt"
  #- "../saved_models/cityscapes_vit_base_1.ckpt"
  #- "../saved_models/potsdam_test.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
