output_root: '../'
pytorch_data_dir: '/old_home_that_will_be_deleted_at_some_point/xinyang/CutLER/datasets/cityscapes_val_reized_raw'
experiment_name: "coco_train"
res: 448
# batch_size: 8
batch_size: 4
num_workers: 16
# num_workers: 24
run_picie: False
# run_picie: True
run_crf: True
# run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False

model_paths:
  - "../saved_models/cocostuff27_vit_base_5.ckpt"
  #- "../saved_models/cityscapes_vit_base_1.ckpt"
  #- "../saved_models/potsdam_test.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
